"""Generate reviewable JSON fixtures from the Python reference helpers."""

import argparse
import json
from pathlib import Path

import numpy as np

from .attention_ref import (
    direct_latent_gqa_decode_attention_intermediates_ref,
    direct_paged_latent_gqa_decode_attention_intermediates_ref,
    direct_paged_latent_gqa_fp16_storage_intermediates_ref,
    direct_paged_latent_gqa_fp16_storage_runtime_intermediates_ref,
    gqa_decode_attention_intermediates_ref,
    latent_kv_decode_attention_intermediates_ref,
    latent_kv_reconstruction_ref,
    paged_gqa_decode_attention_intermediates_ref,
    paged_latent_kv_decode_attention_intermediates_ref,
    paged_lookup_ref,
)
from .block_table import PagedBlockTable
from .cache_ref import (
    fp16_storage_bits,
    fp16_storage_roundtrip_f32,
    paged_kv_write_ref,
    paged_latent_write_fp16_storage_ref,
    paged_latent_write_ref,
    resolve_paged_token_location,
)
from .memory_model import (
    compression_ratio,
    estimate_total_kv_cache_bytes,
    kv_bytes_per_token_gqa,
    kv_bytes_per_token_latent,
)


def memory_model_fixture() -> dict:
    """Return the deterministic small memory-model fixture."""
    config = {
        "layers": 24,
        "seq_len": 128,
        "batch": 1,
        "kv_heads": 2,
        "head_dim": 32,
        "latent_dim": 32,
        "dtype_bytes": 2,
    }
    gqa_bytes = kv_bytes_per_token_gqa(
        config["kv_heads"], config["head_dim"], config["dtype_bytes"]
    )
    latent_bytes = kv_bytes_per_token_latent(config["latent_dim"], config["dtype_bytes"])
    return {
        "config": config,
        "gqa_bytes_per_token_per_layer": gqa_bytes,
        "latent_bytes_per_token_per_layer": latent_bytes,
        "gqa_total_kv_bytes": estimate_total_kv_cache_bytes(
            config["layers"], config["seq_len"], config["batch"], gqa_bytes
        ),
        "latent_total_kv_bytes": estimate_total_kv_cache_bytes(
            config["layers"], config["seq_len"], config["batch"], latent_bytes
        ),
        "compression_ratio_vs_gqa": compression_ratio(gqa_bytes, latent_bytes),
    }


def block_table_fixture(seq_len: int, block_size: int) -> dict:
    """Return token locations generated by the Python block-table model."""
    table = PagedBlockTable(block_size=block_size)
    table.allocate_token_positions(seq_len)
    token_locations = []
    for token in range(seq_len):
        logical_block = token // block_size
        physical_block, offset = table.translate(token)
        token_locations.append(
            {
                "token": token,
                "logical_block": logical_block,
                "physical_block": physical_block,
                "offset": offset,
            }
        )
    return {
        "seq_len": seq_len,
        "block_size": block_size,
        "logical_blocks": table.to_numpy(),
        "token_locations": token_locations,
    }


def paged_lookup_f32_fixture() -> dict:
    """Return a deterministic non-identity paged lookup fixture."""
    seq_len = 5
    block_size = 2
    width = 4
    block_table = np.asarray([2, 0, 1], dtype=np.int32)
    physical_blocks = np.asarray(
        [
            [[0.0, 1.0, 2.0, 3.0], [4.0, 5.0, 6.0, 7.0]],
            [[10.0, 11.0, 12.0, 13.0], [14.0, 15.0, 16.0, 17.0]],
            [[20.0, 21.0, 22.0, 23.0], [24.0, 25.0, 26.0, 27.0]],
        ],
        dtype=np.float32,
    )
    expected = paged_lookup_ref(physical_blocks, block_table, seq_len, block_size)
    return {
        "dtype": "f32",
        "seq_len": seq_len,
        "block_size": block_size,
        "width": width,
        "num_physical_blocks": 3,
        "block_table": block_table.tolist(),
        "physical_blocks": physical_blocks.tolist(),
        "expected_logical_output": expected.tolist(),
    }


def paged_kv_write_fixture() -> dict:
    """Return deterministic full-cache K/V write cases."""
    num_physical_blocks = 4
    block_size = 2
    kv_heads = 2
    head_dim = 4
    width = kv_heads * head_dim
    block_table = np.asarray([2, 0, 1], dtype=np.int32)
    padded_block_table = np.asarray([2, 0, 1, 3], dtype=np.int32)
    initial_k = np.arange(num_physical_blocks * block_size * width, dtype=np.float32).reshape(
        num_physical_blocks, block_size, width
    )
    initial_v = (
        np.arange(num_physical_blocks * block_size * width, dtype=np.float32) + 1000
    ).reshape(num_physical_blocks, block_size, width)
    writes = (
        (
            "position_3_offset_1",
            3,
            np.arange(100, 108, dtype=np.float32),
            np.arange(200, 208, dtype=np.float32),
        ),
        (
            "position_4_offset_0",
            4,
            np.arange(300, 308, dtype=np.float32),
            np.arange(400, 408, dtype=np.float32),
        ),
    )
    cases = []
    for name, token_position, new_k, new_v in writes:
        logical_block, physical_block, block_offset = resolve_paged_token_location(
            block_table, token_position, block_size
        )
        expected_k, expected_v = paged_kv_write_ref(
            initial_k, initial_v, block_table, token_position, new_k, new_v
        )
        cases.append(
            {
                "name": name,
                "token_position": token_position,
                "logical_block": logical_block,
                "physical_block": physical_block,
                "block_offset": block_offset,
                "initial_k_cache": initial_k.tolist(),
                "initial_v_cache": initial_v.tolist(),
                "new_k": new_k.tolist(),
                "new_v": new_v.tolist(),
                "expected_k_cache": expected_k.tolist(),
                "expected_v_cache": expected_v.tolist(),
            }
        )
    return {
        "dtype": "f32",
        "num_physical_blocks": num_physical_blocks,
        "block_size": block_size,
        "kv_heads": kv_heads,
        "head_dim": head_dim,
        "width": width,
        "block_table": block_table.tolist(),
        "gpu_padded_block_table": padded_block_table.tolist(),
        "cases": cases,
    }


def _to_head_major(cache: np.ndarray) -> np.ndarray:
    """Convert [seq_len, kv_heads, head_dim] to [kv_heads, seq_len, head_dim]."""
    return np.transpose(cache, (1, 0, 2)).copy()


def _physical_to_gpu_head_major(cache: np.ndarray) -> np.ndarray:
    """Convert physical token-major blocks to the GPU head-major block layout."""
    return np.transpose(cache, (0, 2, 1, 3)).copy()


def _balanced_gqa_case() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    q_heads = 4
    kv_heads = 2
    seq_len = 8
    head_dim = 8
    q = np.zeros((1, q_heads, head_dim), dtype=np.float32)
    k = np.zeros((1, seq_len, kv_heads, head_dim), dtype=np.float32)
    v = np.zeros((1, seq_len, kv_heads, head_dim), dtype=np.float32)
    for q_head in range(q_heads):
        for dim in range(head_dim):
            q[0, q_head, dim] = (
                (q_head + 1) * 0.17 + (dim + 1) * 0.031 + ((q_head + dim) % 3) * 0.007
            )
    for token in range(seq_len):
        for kv_head in range(kv_heads):
            for dim in range(head_dim):
                k[0, token, kv_head, dim] = (
                    (kv_head + 1) * 0.23
                    + (token + 1) * 0.019
                    - (dim + 1) * 0.011
                    + ((token + dim + kv_head) % 4) * 0.005
                )
                v[0, token, kv_head, dim] = (
                    (kv_head + 1) * 0.41
                    - (token + 1) * 0.013
                    + (dim + 1) * 0.027
                    + ((2 * token + dim + kv_head) % 5) * 0.003
                )
    return q, k, v


def _stable_softmax_gqa_case() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    q_heads = 4
    kv_heads = 2
    seq_len = 8
    head_dim = 8
    q = np.zeros((1, q_heads, head_dim), dtype=np.float32)
    k = np.zeros((1, seq_len, kv_heads, head_dim), dtype=np.float32)
    v = np.zeros((1, seq_len, kv_heads, head_dim), dtype=np.float32)
    for q_head in range(q_heads):
        sign = -1.0 if q_head % 2 else 1.0
        for dim in range(head_dim):
            q[0, q_head, dim] = sign * (6.0 + q_head * 1.25 + dim * 0.5)
    for token in range(seq_len):
        for kv_head in range(kv_heads):
            token_scale = (token - 3.5) * (1.6 + kv_head * 0.35)
            for dim in range(head_dim):
                k[0, token, kv_head, dim] = token_scale + dim * 0.42 - kv_head * 0.9
                v[0, token, kv_head, dim] = (
                    (token + 1) * 0.21 + (kv_head + 1) * 0.33 - dim * 0.017
                )
    return q, k, v


def _gqa_case(name: str, q: np.ndarray, k: np.ndarray, v: np.ndarray) -> dict:
    scores, probabilities, context = gqa_decode_attention_intermediates_ref(
        q, k, v, group_size=2
    )
    return {
        "name": name,
        "q": q[0].tolist(),
        "k_token_major": k[0].tolist(),
        "v_token_major": v[0].tolist(),
        "k_head_major": _to_head_major(k[0]).tolist(),
        "v_head_major": _to_head_major(v[0]).tolist(),
        "expected_scores": scores[0].tolist(),
        "expected_probabilities": probabilities[0].tolist(),
        "expected_context": context[0].tolist(),
    }


def gqa_decode_f32_fixture() -> dict:
    """Return deterministic contiguous GQA decode fixtures with intermediates."""
    q_heads = 4
    kv_heads = 2
    group_size = 2
    seq_len = 8
    head_dim = 8
    balanced_q, balanced_k, balanced_v = _balanced_gqa_case()
    stable_q, stable_k, stable_v = _stable_softmax_gqa_case()
    return {
        "dtype": "f32",
        "batch": 1,
        "q_heads": q_heads,
        "kv_heads": kv_heads,
        "group_size": group_size,
        "seq_len": seq_len,
        "head_dim": head_dim,
        "scale": 1.0 / np.sqrt(float(head_dim)),
        "q_to_kv": (np.arange(q_heads) // group_size).tolist(),
        "cases": [
            _gqa_case("balanced", balanced_q, balanced_k, balanced_v),
            _gqa_case("stable_softmax", stable_q, stable_k, stable_v),
        ],
    }


def _to_physical_blocks(
    token_major: np.ndarray, block_table: np.ndarray, block_size: int
) -> np.ndarray:
    """Map logical token-major cache [seq_len, kv_heads, head_dim] into physical blocks."""
    num_logical_blocks = len(block_table)
    pad_tokens = num_logical_blocks * block_size - token_major.shape[0]
    padded = np.pad(token_major, ((0, pad_tokens), (0, 0), (0, 0)))
    logical_blocks = padded.reshape(num_logical_blocks, block_size, *token_major.shape[1:])
    physical_blocks = np.empty_like(logical_blocks)
    for logical_block, physical_block in enumerate(block_table):
        physical_blocks[physical_block] = logical_blocks[logical_block]
    return physical_blocks


def _paged_gqa_case(name: str, q: np.ndarray, k: np.ndarray, v: np.ndarray) -> dict:
    block_table = np.asarray([2, 0, 3, 1], dtype=np.int32)
    block_size = 2
    k_physical = _to_physical_blocks(k[0], block_table, block_size)
    v_physical = _to_physical_blocks(v[0], block_table, block_size)
    scores, probabilities, context = paged_gqa_decode_attention_intermediates_ref(
        q,
        k_physical,
        v_physical,
        block_table,
        seq_len=8,
        block_size=block_size,
        group_size=2,
    )
    return {
        "name": name,
        "q": q[0].tolist(),
        "k_physical_token_major": k_physical.tolist(),
        "v_physical_token_major": v_physical.tolist(),
        "k_physical_gpu_head_major": _physical_to_gpu_head_major(k_physical).tolist(),
        "v_physical_gpu_head_major": _physical_to_gpu_head_major(v_physical).tolist(),
        "expected_scores": scores[0].tolist(),
        "expected_probabilities": probabilities[0].tolist(),
        "expected_context": context[0].tolist(),
    }


def paged_gqa_decode_f32_fixture() -> dict:
    """Return deterministic direct paged GQA fixtures with physical K/V layouts."""
    q_heads = 4
    kv_heads = 2
    group_size = 2
    seq_len = 8
    head_dim = 8
    block_size = 2
    block_table = np.asarray([2, 0, 3, 1], dtype=np.int32)
    balanced_q, balanced_k, balanced_v = _balanced_gqa_case()
    stable_q, stable_k, stable_v = _stable_softmax_gqa_case()
    return {
        "dtype": "f32",
        "batch": 1,
        "q_heads": q_heads,
        "kv_heads": kv_heads,
        "group_size": group_size,
        "seq_len": seq_len,
        "head_dim": head_dim,
        "block_size": block_size,
        "num_logical_blocks": 4,
        "num_physical_blocks": 4,
        "block_table": block_table.tolist(),
        "scale": 1.0 / np.sqrt(float(head_dim)),
        "q_to_kv": (np.arange(q_heads) // group_size).tolist(),
        "cases": [
            _paged_gqa_case("balanced", balanced_q, balanced_k, balanced_v),
            _paged_gqa_case("stable_softmax", stable_q, stable_k, stable_v),
        ],
    }


def _latent_balanced_projection_case() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    seq_len = 8
    latent_dim = 8
    projection_width = 16
    latent = np.zeros((1, seq_len, latent_dim), dtype=np.float32)
    k_proj = np.zeros((latent_dim, projection_width), dtype=np.float32)
    v_proj = np.zeros((latent_dim, projection_width), dtype=np.float32)
    for token in range(seq_len):
        for dim in range(latent_dim):
            latent[0, token, dim] = (
                (token + 1) * 0.11
                - (dim + 1) * 0.037
                + ((token + dim) % 3) * 0.013
            )
    for latent_idx in range(latent_dim):
        for out_idx in range(projection_width):
            k_proj[latent_idx, out_idx] = (
                (latent_idx + 1) * 0.021
                - (out_idx + 1) * 0.009
                + ((latent_idx * 2 + out_idx) % 5) * 0.004
            )
            v_proj[latent_idx, out_idx] = (
                -(latent_idx + 1) * 0.017
                + (out_idx + 1) * 0.012
                - ((latent_idx + out_idx * 3) % 7) * 0.003
            )
    return latent, k_proj, v_proj


def _latent_signed_accumulation_case() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    seq_len = 8
    latent_dim = 8
    projection_width = 16
    latent = np.zeros((1, seq_len, latent_dim), dtype=np.float32)
    k_proj = np.zeros((latent_dim, projection_width), dtype=np.float32)
    v_proj = np.zeros((latent_dim, projection_width), dtype=np.float32)
    for token in range(seq_len):
        for dim in range(latent_dim):
            sign = -1.0 if (token + dim) % 2 else 1.0
            latent[0, token, dim] = sign * (
                0.19 + token * 0.023 + dim * 0.017 + ((token * dim) % 3) * 0.011
            )
    for latent_idx in range(latent_dim):
        for out_idx in range(projection_width):
            k_sign = -1.0 if (latent_idx + out_idx) % 2 else 1.0
            v_sign = -1.0 if (latent_idx * 3 + out_idx) % 2 else 1.0
            k_proj[latent_idx, out_idx] = k_sign * (
                0.031 + latent_idx * 0.006 - out_idx * 0.0015
            )
            v_proj[latent_idx, out_idx] = v_sign * (
                0.027 - latent_idx * 0.002 + out_idx * 0.004
            )
    return latent, k_proj, v_proj


def _head_major_from_batched_token_major(cache: np.ndarray) -> np.ndarray:
    """Convert [1, seq_len, kv_heads, head_dim] to [kv_heads, seq_len, head_dim]."""
    return np.transpose(cache[0], (1, 0, 2)).copy()


def _projection_to_gpu_head_major(
    projection: np.ndarray, kv_heads: int, head_dim: int
) -> np.ndarray:
    """Convert [latent_dim, kv_heads * head_dim] into [kv_heads, latent_dim, head_dim]."""
    if projection.ndim != 2:
        raise ValueError("projection must be 2D")
    if projection.shape[1] != kv_heads * head_dim:
        raise ValueError("projection width must equal kv_heads * head_dim")
    latent_dim = projection.shape[0]
    return projection.reshape(latent_dim, kv_heads, head_dim).transpose(1, 0, 2).copy()


def _latent_kv_reconstruction_case(
    name: str, latent: np.ndarray, k_proj: np.ndarray, v_proj: np.ndarray
) -> dict:
    k_cache, v_cache = latent_kv_reconstruction_ref(
        latent,
        k_proj,
        v_proj,
        kv_heads=2,
        head_dim=8,
    )
    return {
        "name": name,
        "latent_cache": latent[0].tolist(),
        "k_projection": k_proj.tolist(),
        "v_projection": v_proj.tolist(),
        "expected_k_token_major": k_cache[0].tolist(),
        "expected_v_token_major": v_cache[0].tolist(),
        "expected_k_head_major": _head_major_from_batched_token_major(k_cache).tolist(),
        "expected_v_head_major": _head_major_from_batched_token_major(v_cache).tolist(),
    }


def latent_kv_reconstruction_f32_fixture() -> dict:
    """Return deterministic MLA-style synthetic latent-KV reconstruction fixtures."""
    seq_len = 8
    latent_dim = 8
    kv_heads = 2
    head_dim = 8
    projection_width = kv_heads * head_dim
    balanced_latent, balanced_k_proj, balanced_v_proj = _latent_balanced_projection_case()
    signed_latent, signed_k_proj, signed_v_proj = _latent_signed_accumulation_case()
    return {
        "dtype": "f32",
        "batch": 1,
        "seq_len": seq_len,
        "latent_dim": latent_dim,
        "kv_heads": kv_heads,
        "head_dim": head_dim,
        "projection_width": projection_width,
        "latent_values_per_token": latent_dim,
        "full_kv_values_per_token": 2 * kv_heads * head_dim,
        "theoretical_cache_compression_ratio": (2 * kv_heads * head_dim) / latent_dim,
        "cases": [
            _latent_kv_reconstruction_case(
                "balanced_projection", balanced_latent, balanced_k_proj, balanced_v_proj
            ),
            _latent_kv_reconstruction_case(
                "signed_accumulation", signed_latent, signed_k_proj, signed_v_proj
            ),
        ],
    }


def _direct_latent_case(
    name: str, q: np.ndarray, latent: np.ndarray, k_proj: np.ndarray, v_proj: np.ndarray
) -> dict:
    direct_scores, direct_probs, direct_context = (
        direct_latent_gqa_decode_attention_intermediates_ref(
        q,
        latent,
        k_proj,
        v_proj,
        q_heads=4,
        kv_heads=2,
        head_dim=8,
        group_size=2,
        )
    )
    materialized_scores, materialized_probs, materialized_context = (
        latent_kv_decode_attention_intermediates_ref(
            q,
            latent,
            k_proj,
            v_proj,
            q_heads=4,
            kv_heads=2,
            head_dim=8,
            group_size=2,
        )
    )
    return {
        "name": name,
        "q": q[0].tolist(),
        "latent_cache": latent[0].tolist(),
        "k_projection": k_proj.tolist(),
        "v_projection": v_proj.tolist(),
        "k_projection_gpu_head_major": _projection_to_gpu_head_major(k_proj, 2, 8).tolist(),
        "v_projection_gpu_head_major": _projection_to_gpu_head_major(v_proj, 2, 8).tolist(),
        "expected_scores": direct_scores[0].tolist(),
        "expected_probabilities": direct_probs[0].tolist(),
        "expected_context": direct_context[0].tolist(),
        "materialized_scores": materialized_scores[0].tolist(),
        "materialized_probabilities": materialized_probs[0].tolist(),
        "materialized_context": materialized_context[0].tolist(),
    }


def direct_latent_gqa_decode_f32_fixture() -> dict:
    """Return deterministic direct latent-space GQA fixtures."""
    q_heads = 4
    kv_heads = 2
    group_size = 2
    seq_len = 8
    latent_dim = 8
    head_dim = 8
    projection_width = kv_heads * head_dim
    balanced_q, _, _ = _balanced_gqa_case()
    stable_q, _, _ = _stable_softmax_gqa_case()
    balanced_latent, balanced_k_proj, balanced_v_proj = _latent_balanced_projection_case()
    signed_latent, signed_k_proj, signed_v_proj = _latent_signed_accumulation_case()
    stable_scale = np.float32(32.0)
    return {
        "dtype": "f32",
        "batch": 1,
        "seq_len": seq_len,
        "q_heads": q_heads,
        "kv_heads": kv_heads,
        "group_size": group_size,
        "head_dim": head_dim,
        "latent_dim": latent_dim,
        "projection_width": projection_width,
        "q_to_kv": (np.arange(q_heads) // group_size).tolist(),
        "scale": 1.0 / np.sqrt(float(head_dim)),
        "latent_values_per_token": latent_dim,
        "full_kv_values_per_token": 2 * kv_heads * head_dim,
        "theoretical_cache_compression_ratio": (2 * kv_heads * head_dim) / latent_dim,
        "cases": [
            _direct_latent_case(
                "balanced_attention",
                balanced_q,
                balanced_latent,
                balanced_k_proj,
                balanced_v_proj,
            ),
            _direct_latent_case(
                "stable_softmax_attention",
                stable_q * stable_scale,
                signed_latent,
                signed_k_proj,
                signed_v_proj,
            ),
        ],
    }


def direct_paged_latent_gqa_decode_f32_fixture() -> dict:
    """Return the fixed non-identity direct paged latent fixture."""
    base = direct_latent_gqa_decode_f32_fixture()
    table = np.asarray([2, 0, 3, 1], dtype=np.int32)
    cases = []
    for source in base["cases"]:
        latent = np.asarray(source["latent_cache"], dtype=np.float32)
        physical = np.empty((4, 2, 8), dtype=np.float32)
        logical = latent.reshape(4, 2, 8)
        for logical_block, physical_block in enumerate(table):
            physical[physical_block] = logical[logical_block]
        q = np.asarray(source["q"], dtype=np.float32)[None, ...]
        kp = np.asarray(source["k_projection"], dtype=np.float32)
        vp = np.asarray(source["v_projection"], dtype=np.float32)
        direct = direct_paged_latent_gqa_decode_attention_intermediates_ref(
            q, physical, table, 8, 2, kp, vp, q_heads=4, kv_heads=2, head_dim=8, group_size=2
        )
        materialized = paged_latent_kv_decode_attention_intermediates_ref(
            q, physical, table, 8, 2, kp, vp, q_heads=4, kv_heads=2, head_dim=8, group_size=2
        )
        contiguous = direct_latent_gqa_decode_attention_intermediates_ref(
            q, latent[None, ...], kp, vp, q_heads=4, kv_heads=2, head_dim=8, group_size=2
        )
        cases.append({
            "name": source["name"], "q": source["q"],
            "latent_physical_blocks": physical.tolist(), "k_projection": kp.tolist(),
            "v_projection": vp.tolist(),
            "k_projection_gpu_head_major": source["k_projection_gpu_head_major"],
            "v_projection_gpu_head_major": source["v_projection_gpu_head_major"],
            "expected_scores": direct[0][0].tolist(),
            "expected_probabilities": direct[1][0].tolist(),
            "expected_context": direct[2][0].tolist(),
            "materialized_scores": materialized[0][0].tolist(),
            "materialized_probabilities": materialized[1][0].tolist(),
            "materialized_context": materialized[2][0].tolist(),
            "contiguous_direct_scores": contiguous[0][0].tolist(),
            "contiguous_direct_probabilities": contiguous[1][0].tolist(),
            "contiguous_direct_context": contiguous[2][0].tolist(),
        })
    return {"dtype":"f32", "batch":1, "seq_len":8, "q_heads":4, "kv_heads":2, "group_size":2,
            "head_dim":8, "latent_dim":8, "block_size":2, "num_logical_blocks":4,
            "num_physical_blocks":4, "block_table":table.tolist(), "q_to_kv":[0,0,1,1],
            "scale":1.0 / np.sqrt(8.0), "latent_values_per_token":8, "full_kv_values_per_token":32,
            "theoretical_cache_compression_ratio":4.0, "cases":cases}


def paged_latent_write_attention_f32_fixture() -> dict:
    """Return deterministic write-to-attention round-trip fixtures."""
    base = direct_paged_latent_gqa_decode_f32_fixture()
    table = np.asarray(base["block_table"], dtype=np.int32)
    write_specs = [
        (
            "balanced_position_3_offset_1",
            3,
            np.array(
                [0.73, -0.41, 1.17, -0.29, 0.58, -0.86, 0.34, 1.02],
                dtype=np.float32,
            ),
        ),
        (
            "stable_position_4_offset_0",
            4,
            np.array(
                [-1.11, 0.47, -0.68, 1.26, -0.35, 0.92, -0.79, 0.18],
                dtype=np.float32,
            ),
        ),
    ]
    cases = []
    for source, (name, token_position, new_latent) in zip(base["cases"], write_specs, strict=True):
        initial = np.asarray(source["latent_physical_blocks"], dtype=np.float32)
        updated = paged_latent_write_ref(initial, table, token_position, new_latent)
        q = np.asarray(source["q"], dtype=np.float32)[None, ...]
        kp = np.asarray(source["k_projection"], dtype=np.float32)
        vp = np.asarray(source["v_projection"], dtype=np.float32)
        pre = direct_paged_latent_gqa_decode_attention_intermediates_ref(
            q, initial, table, 8, 2, kp, vp, q_heads=4, kv_heads=2, head_dim=8, group_size=2
        )
        post = direct_paged_latent_gqa_decode_attention_intermediates_ref(
            q, updated, table, 8, 2, kp, vp, q_heads=4, kv_heads=2, head_dim=8, group_size=2
        )
        logical_block, physical_block, block_offset = resolve_paged_token_location(
            table, token_position, 2
        )
        cases.append({
            "name": name, "token_position": token_position,
            "logical_block": logical_block, "physical_block": physical_block,
            "block_offset": block_offset, "q": source["q"],
            "initial_latent_physical_blocks": initial.tolist(),
            "new_latent": new_latent.tolist(),
            "expected_updated_latent_physical_blocks": updated.tolist(),
            "k_projection": source["k_projection"], "v_projection": source["v_projection"],
            "k_projection_gpu_head_major": source["k_projection_gpu_head_major"],
            "v_projection_gpu_head_major": source["v_projection_gpu_head_major"],
            "pre_write_scores": pre[0][0].tolist(),
            "pre_write_probabilities": pre[1][0].tolist(),
            "pre_write_context": pre[2][0].tolist(),
            "post_write_scores": post[0][0].tolist(),
            "post_write_probabilities": post[1][0].tolist(),
            "post_write_context": post[2][0].tolist(),
        })
    return {
        "dtype": "f32", "batch": 1, "seq_len": 8, "q_heads": 4, "kv_heads": 2,
        "group_size": 2, "head_dim": 8, "latent_dim": 8, "block_size": 2,
        "num_logical_blocks": 4, "num_physical_blocks": 4, "block_table": table.tolist(),
        "q_to_kv": [0, 0, 1, 1], "theoretical_cache_compression_ratio": 4.0,
        "cases": cases,
    }


def paged_latent_write_attention_fp16_storage_fixture() -> dict:
    """Return FP16-storage write-to-attention fixtures with FP32 arithmetic."""
    base = paged_latent_write_attention_f32_fixture()
    cases = []
    for source in base["cases"]:
        initial_source = np.asarray(
            source["initial_latent_physical_blocks"], dtype=np.float32
        )
        new_source = np.asarray(source["new_latent"], dtype=np.float32)
        initial_stored = fp16_storage_roundtrip_f32(initial_source)
        new_stored = fp16_storage_roundtrip_f32(new_source)
        updated_stored = paged_latent_write_fp16_storage_ref(
            initial_source,
            np.asarray(base["block_table"], dtype=np.int32),
            source["token_position"],
            new_source,
        )
        q = np.asarray(source["q"], dtype=np.float32)[None, ...]
        kp = np.asarray(source["k_projection"], dtype=np.float32)
        vp = np.asarray(source["v_projection"], dtype=np.float32)
        fp32_pre = (
            np.asarray(source["pre_write_scores"], dtype=np.float32),
            np.asarray(source["pre_write_probabilities"], dtype=np.float32),
            np.asarray(source["pre_write_context"], dtype=np.float32),
        )
        fp32_post = (
            np.asarray(source["post_write_scores"], dtype=np.float32),
            np.asarray(source["post_write_probabilities"], dtype=np.float32),
            np.asarray(source["post_write_context"], dtype=np.float32),
        )
        fp16_pre = direct_paged_latent_gqa_fp16_storage_intermediates_ref(
            q, initial_source, np.asarray(base["block_table"], dtype=np.int32), 8, 2,
            kp, vp, q_heads=4, kv_heads=2, head_dim=8, group_size=2,
        )
        fp16_post = direct_paged_latent_gqa_fp16_storage_intermediates_ref(
            q, updated_stored, np.asarray(base["block_table"], dtype=np.int32), 8, 2,
            kp, vp, q_heads=4, kv_heads=2, head_dim=8, group_size=2,
        )
        cases.append({
            "name": source["name"], "token_position": source["token_position"],
            "logical_block": source["logical_block"], "physical_block": source["physical_block"],
            "block_offset": source["block_offset"], "q": source["q"],
            "initial_latent_source_f32": initial_source.tolist(),
            "initial_latent_stored_fp16_as_f32": initial_stored.tolist(),
            "initial_latent_fp16_bits": fp16_storage_bits(initial_source).tolist(),
            "new_latent_source_f32": new_source.tolist(),
            "new_latent_stored_fp16_as_f32": new_stored.tolist(),
            "new_latent_fp16_bits": fp16_storage_bits(new_source).tolist(),
            "expected_updated_latent_fp16_as_f32": updated_stored.tolist(),
            "expected_updated_latent_fp16_bits": fp16_storage_bits(updated_stored).tolist(),
            "k_projection": source["k_projection"], "v_projection": source["v_projection"],
            "k_projection_gpu_head_major": source["k_projection_gpu_head_major"],
            "v_projection_gpu_head_major": source["v_projection_gpu_head_major"],
            "fp32_pre_write_scores": fp32_pre[0].tolist(),
            "fp32_pre_write_probabilities": fp32_pre[1].tolist(),
            "fp32_pre_write_context": fp32_pre[2].tolist(),
            "fp32_post_write_scores": fp32_post[0].tolist(),
            "fp32_post_write_probabilities": fp32_post[1].tolist(),
            "fp32_post_write_context": fp32_post[2].tolist(),
            "fp16_storage_pre_write_scores": fp16_pre[0][0].tolist(),
            "fp16_storage_pre_write_probabilities": fp16_pre[1][0].tolist(),
            "fp16_storage_pre_write_context": fp16_pre[2][0].tolist(),
            "fp16_storage_post_write_scores": fp16_post[0][0].tolist(),
            "fp16_storage_post_write_probabilities": fp16_post[1][0].tolist(),
            "fp16_storage_post_write_context": fp16_post[2][0].tolist(),
        })
    return {
        "storage_dtype": "f16", "compute_dtype": "f32", "write_input_dtype": "f32",
        "batch": 1, "seq_len": 8, "q_heads": 4, "kv_heads": 2, "group_size": 2,
        "head_dim": 8, "latent_dim": 8, "block_size": 2, "num_logical_blocks": 4,
        "num_physical_blocks": 4, "block_table": [2, 0, 3, 1], "q_to_kv": [0, 0, 1, 1],
        "latent_cache_values": 64, "latent_cache_bytes_fp16": 128,
        "latent_cache_bytes_fp32": 256, "hypothetical_full_kv_cache_bytes_fp16": 512,
        "stored_cache_ratio_vs_fp16_full_kv": 4.0, "latent_storage_ratio_fp32_to_fp16": 2.0,
        "cases": cases,
    }


def runtime_sequence_tiny_fp16_storage_fixture() -> dict:
    """Return complete tiny runtime active-length golden data."""
    base = paged_latent_write_attention_fp16_storage_fixture()
    active_lengths = [1, 3, 4, 7, 8]
    cases = []
    for base_case in base["cases"]:
        runtime_cases = []
        q = np.asarray(base_case["q"], dtype=np.float32)[None, ...]
        latent = np.asarray(base_case["initial_latent_source_f32"], dtype=np.float32)
        table = np.asarray(base["block_table"], dtype=np.int64)
        k_projection = np.asarray(base_case["k_projection"], dtype=np.float32)
        v_projection = np.asarray(base_case["v_projection"], dtype=np.float32)
        for active_seq_len in active_lengths:
            scores, probabilities, context = (
                direct_paged_latent_gqa_fp16_storage_runtime_intermediates_ref(
                    q,
                    latent,
                    table,
                    base["seq_len"],
                    active_seq_len,
                    base["block_size"],
                    k_projection,
                    v_projection,
                    q_heads=base["q_heads"],
                    kv_heads=base["kv_heads"],
                    head_dim=base["head_dim"],
                    group_size=base["group_size"],
                )
            )
            inactive = probabilities[:, :, active_seq_len:]
            runtime_cases.append(
                {
                    "active_seq_len": active_seq_len,
                    "active_logical_blocks": int(
                        np.ceil(active_seq_len / float(base["block_size"]))
                    ),
                    "scores": scores[0].tolist(),
                    "probabilities": probabilities[0].tolist(),
                    "context": context[0].tolist(),
                    "inactive_probabilities_zero": bool(np.all(inactive == 0.0)),
                    "max_probability_row_sum_error": float(
                        np.max(np.abs(probabilities.sum(axis=-1) - 1.0))
                    ),
                }
            )
        cases.append(
            {
                "name": base_case["name"],
                "q": base_case["q"],
                "initial_latent_source_f32": base_case["initial_latent_source_f32"],
                "initial_latent_stored_fp16_as_f32": base_case[
                    "initial_latent_stored_fp16_as_f32"
                ],
                "initial_latent_fp16_bits": base_case["initial_latent_fp16_bits"],
                "k_projection": base_case["k_projection"],
                "v_projection": base_case["v_projection"],
                "k_projection_gpu_head_major": base_case["k_projection_gpu_head_major"],
                "v_projection_gpu_head_major": base_case["v_projection_gpu_head_major"],
                "runtime_cases": runtime_cases,
            }
        )
    return {
        "profile": "tiny",
        "storage_dtype": "f16",
        "compute_dtype": "f32",
        "batch": base["batch"],
        "max_seq_len": base["seq_len"],
        "active_seq_lens": active_lengths,
        "q_heads": base["q_heads"],
        "kv_heads": base["kv_heads"],
        "group_size": base["group_size"],
        "head_dim": base["head_dim"],
        "latent_dim": base["latent_dim"],
        "block_size": base["block_size"],
        "num_logical_blocks": base["num_logical_blocks"],
        "num_physical_blocks": base["num_physical_blocks"],
        "block_table": base["block_table"],
        "q_to_kv": base["q_to_kv"],
        "cases": cases,
    }


def write_fixtures(out_dir: str | Path) -> list[Path]:
    """Write all committed reference fixtures and return their paths."""
    destination = Path(out_dir)
    destination.mkdir(parents=True, exist_ok=True)
    fixtures = {
        "memory_model_small.json": memory_model_fixture(),
        "block_table_seq5_block2.json": block_table_fixture(5, 2),
        "block_table_seq128_block16.json": block_table_fixture(128, 16),
        "paged_lookup_f32_seq5_block2_width4.json": paged_lookup_f32_fixture(),
        "paged_kv_write_f32.json": paged_kv_write_fixture(),
        "gqa_decode_f32.json": gqa_decode_f32_fixture(),
        "paged_gqa_decode_f32.json": paged_gqa_decode_f32_fixture(),
        "latent_kv_reconstruction_f32.json": latent_kv_reconstruction_f32_fixture(),
        "direct_latent_gqa_decode_f32.json": direct_latent_gqa_decode_f32_fixture(),
        "direct_paged_latent_gqa_decode_f32.json": direct_paged_latent_gqa_decode_f32_fixture(),
        "paged_latent_write_attention_f32.json": paged_latent_write_attention_f32_fixture(),
        "paged_latent_write_attention_fp16_storage.json": (
            paged_latent_write_attention_fp16_storage_fixture()
        ),
        "runtime_sequence_tiny_fp16_storage.json": (
            runtime_sequence_tiny_fp16_storage_fixture()
        ),
    }
    paths = []
    for filename, value in fixtures.items():
        path = destination / filename
        path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")
        paths.append(path)
    return paths


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, required=True)
    args = parser.parse_args()
    for path in write_fixtures(args.out_dir):
        print(path)


if __name__ == "__main__":
    main()
