#!/usr/bin/env python3
"""Generate only the four bounded C1 modules from the reviewed C source."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def generated():
    source = (ROOT/'crates/plkv-kernels/src/cutile/model_profile_preprojected.rs').read_text()
    old = '''        let table_tile: Tile<i32, { [64] }> = table.load_tile(const_shape![64], [0]);
        let selected: Tile<i32, { [1] }> = extract(table_tile, [scalar_to_tile(logical)]);'''
    assert source.count(old) == 1
    source = source.replace(old, '        let selected: Tile<i32, { [1] }> = table.load_tile(const_shape![1], [logical]);')
    return '// Generated by scripts/generate_c1.py; FP32 projection, single-entry paging.\n' + '\n'.join(source.replace('model_profile_preprojected_kernel', f'c1_kernel_{n}').replace('{ [64] }', '{ ['+str(n//16)+'] }') for n in (1024,2048,4096,8192))
if __name__ == '__main__':
    (ROOT/'crates/plkv-kernels/src/cutile/c1.rs').write_text(generated())
