#!/usr/bin/env python3
"""Generate C1 projection/score modules for the Phase-2 sequence sweep."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LENGTHS = (128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768)
HEADER = "// Generated by scripts/generate_c1.py; FP32 projection, single-entry paging.\n"
FULL_TABLE_LOOKUP = (
    "        let table_tile: Tile<i32, { [64] }> = table.load_tile(const_shape![64], [0]);\n"
    "        let selected: Tile<i32, { [1] }> ="
    " extract(table_tile, [scalar_to_tile(logical)]);"
)
SINGLE_ENTRY_LOOKUP = (
    "        let selected: Tile<i32, { [1] }> = table.load_tile(const_shape![1], [logical]);"
)


def specialize(source, n):
    source = source.replace("model_profile_preprojected_kernel", f"c1_kernel_{n}")
    return source.replace("{ [64] }", "{ [" + str(n // 16) + "] }")


def generated():
    path = ROOT / "crates/plkv-kernels/src/cutile/model_profile_preprojected.rs"
    source = path.read_text()
    assert source.count(FULL_TABLE_LOOKUP) == 1
    source = source.replace(FULL_TABLE_LOOKUP, SINGLE_ENTRY_LOOKUP)
    return HEADER + "\n".join(specialize(source, n) for n in LENGTHS)


if __name__ == "__main__":
    (ROOT / "crates/plkv-kernels/src/cutile/c1.rs").write_text(generated())
