"""Generate reviewable JSON fixtures from the Python reference helpers."""

import argparse
import json
from pathlib import Path

import numpy as np

from .attention_ref import paged_lookup_ref
from .block_table import PagedBlockTable
from .memory_model import (
    compression_ratio,
    estimate_total_kv_cache_bytes,
    kv_bytes_per_token_gqa,
    kv_bytes_per_token_latent,
)


def memory_model_fixture() -> dict:
    """Return the deterministic small memory-model fixture."""
    config = {
        "layers": 24,
        "seq_len": 128,
        "batch": 1,
        "kv_heads": 2,
        "head_dim": 32,
        "latent_dim": 32,
        "dtype_bytes": 2,
    }
    gqa_bytes = kv_bytes_per_token_gqa(
        config["kv_heads"], config["head_dim"], config["dtype_bytes"]
    )
    latent_bytes = kv_bytes_per_token_latent(config["latent_dim"], config["dtype_bytes"])
    return {
        "config": config,
        "gqa_bytes_per_token_per_layer": gqa_bytes,
        "latent_bytes_per_token_per_layer": latent_bytes,
        "gqa_total_kv_bytes": estimate_total_kv_cache_bytes(
            config["layers"], config["seq_len"], config["batch"], gqa_bytes
        ),
        "latent_total_kv_bytes": estimate_total_kv_cache_bytes(
            config["layers"], config["seq_len"], config["batch"], latent_bytes
        ),
        "compression_ratio_vs_gqa": compression_ratio(gqa_bytes, latent_bytes),
    }


def block_table_fixture(seq_len: int, block_size: int) -> dict:
    """Return token locations generated by the Python block-table model."""
    table = PagedBlockTable(block_size=block_size)
    table.allocate_token_positions(seq_len)
    token_locations = []
    for token in range(seq_len):
        logical_block = token // block_size
        physical_block, offset = table.translate(token)
        token_locations.append(
            {
                "token": token,
                "logical_block": logical_block,
                "physical_block": physical_block,
                "offset": offset,
            }
        )
    return {
        "seq_len": seq_len,
        "block_size": block_size,
        "logical_blocks": table.to_numpy(),
        "token_locations": token_locations,
    }


def paged_lookup_f32_fixture() -> dict:
    """Return a deterministic non-identity paged lookup fixture."""
    seq_len = 5
    block_size = 2
    width = 4
    block_table = np.asarray([2, 0, 1], dtype=np.int32)
    physical_blocks = np.asarray(
        [
            [[0.0, 1.0, 2.0, 3.0], [4.0, 5.0, 6.0, 7.0]],
            [[10.0, 11.0, 12.0, 13.0], [14.0, 15.0, 16.0, 17.0]],
            [[20.0, 21.0, 22.0, 23.0], [24.0, 25.0, 26.0, 27.0]],
        ],
        dtype=np.float32,
    )
    expected = paged_lookup_ref(physical_blocks, block_table, seq_len, block_size)
    return {
        "dtype": "f32",
        "seq_len": seq_len,
        "block_size": block_size,
        "width": width,
        "num_physical_blocks": 3,
        "block_table": block_table.tolist(),
        "physical_blocks": physical_blocks.tolist(),
        "expected_logical_output": expected.tolist(),
    }


def write_fixtures(out_dir: str | Path) -> list[Path]:
    """Write all committed reference fixtures and return their paths."""
    destination = Path(out_dir)
    destination.mkdir(parents=True, exist_ok=True)
    fixtures = {
        "memory_model_small.json": memory_model_fixture(),
        "block_table_seq5_block2.json": block_table_fixture(5, 2),
        "block_table_seq128_block16.json": block_table_fixture(128, 16),
        "paged_lookup_f32_seq5_block2_width4.json": paged_lookup_f32_fixture(),
    }
    paths = []
    for filename, value in fixtures.items():
        path = destination / filename
        path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")
        paths.append(path)
    return paths


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, required=True)
    args = parser.parse_args()
    for path in write_fixtures(args.out_dir):
        print(path)


if __name__ == "__main__":
    main()
